# Generated by Django 5.0.6 on 2024-05-25 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesqualifications',
            name='changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employeesqualifications',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
