# Generated by Django 4.2 on 2023-04-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
