# Generated by Django 4.2 on 2023-04-26 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_is_external'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'start_contract']},
        ),
        migrations.AddField(
            model_name='user',
            name='end_contract',
            field=models.DateField(blank=True, default='2023-04-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='start_contract',
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
