# Generated by Django 4.2 on 2023-04-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_options_user_end_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_contract',
            field=models.DateField(blank=True, null=True),
        ),
    ]
