# Generated by Django 4.2 on 2023-04-26 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_start_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_contract',
            field=models.DateField(default=datetime.datetime(2023, 4, 26, 7, 33, 37, 261425, tzinfo=datetime.timezone.utc)),
        ),
    ]
