# Generated by Django 4.2 on 2023-04-26 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_start_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_contract',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
