# Generated by Django 4.2 on 2023-04-26 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Qualifications', '0002_rename_important_qualification_is_important'),
        ('Users', '0010_alter_user_start_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Departments.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='holiday_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeesQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifications.qualification')),
            ],
            options={
                'verbose_name': 'EmployeeQualification',
                'verbose_name_plural': 'EmployeeQualifications',
                'ordering': ['employee', 'qualification'],
            },
        ),
    ]
