# Generated by Django 4.2 on 2023-04-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_user_department_user_holiday_count_user_work_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesqualifications',
            name='note',
        ),
    ]
