# Generated by Django 4.2 on 2023-04-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'DayTemplate',
                'verbose_name_plural': 'DayTemplates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DayShiftTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DayTemplates.daytemplate')),
            ],
            options={
                'verbose_name': 'DayShiftTemplate',
                'verbose_name_plural': 'DayShiftTemplates',
                'ordering': ['day_template', 'shift_template'],
            },
        ),
    ]
