# Generated by Django 5.0.6 on 2024-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'sent'), (1, 'not decided'), (2, 'declined'), (3, 'approved')], default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Holidays',
                'verbose_name_plural': 'Holidays',
                'ordering': ['start_date', 'end_date', 'employee'],
            },
        ),
    ]
