# Generated by Django 4.2 on 2023-05-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start_date', 'end_date', 'employee'], 'verbose_name': 'Holidays', 'verbose_name_plural': 'Holidays'},
        ),
    ]
