# Generated by Django 4.2 on 2023-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Holidays', '0002_alter_holiday_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
