# Generated by Django 4.2 on 2023-05-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Availabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['-is_available', 'weekday', 'tendency', 'start_time', 'end_time', 'employee'], 'verbose_name': 'Availability', 'verbose_name_plural': 'Availabilities'},
        ),
    ]
