# Generated by Django 4.2 on 2023-05-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Qualifications', '0002_rename_important_qualification_is_important'),
        ('Departments', '0002_departmentqualifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
                ('break_duration', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('highlight', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Departments.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start', 'end', 'department', 'break_duration', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='ShiftQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifications.qualification')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shifts.shift')),
            ],
            options={
                'verbose_name': 'ShiftQualification',
                'verbose_name_plural': 'ShiftQualifications',
                'ordering': ['shift', 'qualification'],
            },
        ),
    ]
