# Generated by Django 5.0.6 on 2024-05-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Qualifications', '0001_initial'),
        ('Shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftqualifications',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifications.qualification'),
        ),
        migrations.AddField(
            model_name='shiftqualifications',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shifts.shift'),
        ),
    ]
