# Generated by Django 5.0.6 on 2024-05-25 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('reason', models.IntegerField(choices=[(0, 'sickness (without medical proof)'), (1, 'sickness (with medical proof)'), (2, 'private related'), (3, 'business related'), (4, 'other reason')], default=4)),
                ('status', models.IntegerField(choices=[(0, 'sent'), (1, 'not decided'), (2, 'declined'), (3, 'approved')], default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['start_date', 'end_date', 'employee'],
            },
        ),
    ]
