# Generated by Django 4.2 on 2023-05-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Absences', '0002_alter_absence_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['start_date', 'end_date', 'employee'], 'verbose_name': 'Absence', 'verbose_name_plural': 'Absences'},
        ),
    ]
