# Generated by Django 4.2 on 2023-04-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0002_departmentqualifications'),
        ('Qualifications', '0002_rename_important_qualification_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration', models.TimeField()),
                ('note', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.department')),
            ],
            options={
                'verbose_name': 'ShiftTemplate',
                'verbose_name_plural': 'ShiftTemplates',
                'ordering': ['department', 'name', 'start_time', 'end_time', 'break_duration'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplateQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifications.qualification')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShiftTemplates.shifttemplate')),
            ],
            options={
                'verbose_name': 'ShiftTemplateQualification',
                'verbose_name_plural': 'ShiftTemplateQualifications',
                'ordering': ['shift_template', 'qualification'],
            },
        ),
    ]
