# Generated by Django 4.2 on 2023-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShiftTemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttemplate',
            name='break_duration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
