# Generated by Django 4.2 on 2023-04-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='date',
        ),
    ]
