# Generated by Django 4.2 on 2023-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0002_remove_demand_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
