# Generated by Django 4.2 on 2023-05-02 18:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 5, 2, 20, 10, 25, 585980))),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('tendency', models.IntegerField(choices=[(0, 'No preference'), (1, 'Early shift'), (2, 'Midday shift'), (3, 'Late shift'), (4, 'Night shift')], default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wish',
                'verbose_name_plural': 'Wishes',
                'ordering': ['date', '-is_available', 'tendency', 'start_time', 'end_time', 'employee'],
            },
        ),
    ]
