# Generated by Django 4.2 on 2023-05-03 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Wishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
