# Generated by Django 5.0.6 on 2024-05-25 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='import_files', validators=[django.core.validators.FileExtensionValidator(['xlsx'])])),
            ],
        ),
    ]
