# Generated by Django 4.2 on 2023-05-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
