# Generated by Django 4.2 on 2023-04-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifications', '0002_rename_important_qualification_is_important'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.department')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qualifications.qualification')),
            ],
            options={
                'verbose_name': 'DepartmentQualification',
                'verbose_name_plural': 'DepartmentQualifications',
                'ordering': ['department', 'qualification'],
            },
        ),
    ]
