# Generated by Django 4.2 on 2023-04-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qualifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='important',
            new_name='is_important',
        ),
    ]
